In [1]:
import numpy as np

In [2]:
#Numpy배열 생성하기 1 :array()함수
nparr1=np.array(list(range(1,6)))
nparr1

array([1, 2, 3, 4, 5])

In [3]:
f'type:{type(nparr1)},shape:{nparr1.shape},dimensions:{nparr1.ndim},dtype:{nparr1.dtype}'

"type:<class 'numpy.ndarray'>,shape:(5,),dimensions:1,dtype:int32"

In [4]:
nparr2 = np.array([list(range(1,6)),[i for i in range(6,11)]])
nparr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
f'type:{type(nparr2)},shape:{nparr2.shape},dimensions:{nparr2.ndim},dtype:{nparr2.dtype}'

"type:<class 'numpy.ndarray'>,shape:(2, 5),dimensions:2,dtype:int32"

In [6]:
data=[#리스트
        [#axis=0
            [1,2,3],#axis=1
            [4,5,6],
            [7,8,9]
            #각 요소는 axis=2
        ],
        [
            [10,11,12],[13,14,15],[16,17,18]
        ]
    ]
nparr3=np.array(data,dtype=np.float32)
nparr3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]], dtype=float32)

In [7]:
f'type:{type(nparr3)},shape:{nparr3.shape},dimensions:{nparr3.ndim},dtype:{nparr3.dtype}'

"type:<class 'numpy.ndarray'>,shape:(2, 3, 3),dimensions:3,dtype:float32"

In [8]:
npScalar=np.array(100)
npScalar

array(100)

In [9]:
f'type:{type(npScalar)},shape:{npScalar.shape},dimensions:{npScalar.ndim},dtype:{npScalar.dtype}'

"type:<class 'numpy.ndarray'>,shape:(),dimensions:0,dtype:int32"

In [10]:
npArr4=np.array([100])
npArr4

array([100])

In [11]:
f'type:{type(npArr4)},shape:{npArr4.shape},dimensions:{npArr4.ndim},dtype:{npArr4.dtype}'

"type:<class 'numpy.ndarray'>,shape:(1,),dimensions:1,dtype:int32"

In [16]:
#np.inf(infinity):무한대를 의미
#np.nan(not a number):정의할 수 없는 숫자
#RuntimeWarning: divide by zero encountered in divide :숫자 / 0 일때
#invalid value encountered in divide
#위 두 경고를 없애기 위한 코드
np.seterr(divide='ignore',invalid='ignore')
nArr5=np.array([1,0])/np.array([0,0])
nArr5

array([inf, nan])

In [18]:
nArr5[0]==np.inf

True

In [22]:
#np.nan은 숫자가 아니다라 의미지 특정값이 아니다
#따라서  비교연산자로 비교시 항상 False다.비교는  3==5처럼 특정값끼리 비교해야 한다
#넘파이에서 제공하는 isnan()함수로 판단하자
#nArr5[1]==np.nan#항상 False
np.isnan(nArr5[1])

True