In [2]:
#넘파이 배열을 다루는 기타 유용한 함수들
import numpy as np

In [3]:
#np.copy(배열) 혹은 np.ndarray.copy()함수
arr = np.arange(1,11).reshape((5,-1))
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [4]:
arr_=arr.copy()
arr_

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
#np.sort(배열[,axis=-1]) 혹은 np.ndarray.sort([axis=-1])함수
np.random.seed(42)
arr2 = np.random.randint(1,12,(3,4))
arr2.sort(axis=0)
arr2

array([[ 5,  4, 10,  3],
       [ 7,  7, 11,  8],
       [ 7, 11, 11,  8]])

In [13]:
#np.unique()함수
names = np.array(['나길동','가길동','홍길동','다길동','나길동','홍길동'])
'''
return_index : 유니크한 넘파이 배열을 반환할때  그 요소들의 인덱스를 함께 반환할지 여부
return_counts : 유니크한 넘파이 배열을 반환할때 그 요소들의 빈도수를 함께 반환할지 여부
'''
names_ = np.unique(names)
print(names_)
names_.dtype


['가길동' '나길동' '다길동' '홍길동']


dtype('<U3')

In [14]:
names_ = np.unique(names,return_index=True)
names_

(array(['가길동', '나길동', '다길동', '홍길동'], dtype='<U3'),
 array([1, 0, 3, 2], dtype=int64))

In [15]:
names_ = np.unique(names,return_index=True,return_counts=True)
names_#(요소배열,인덱스배열,빈도수배열)

(array(['가길동', '나길동', '다길동', '홍길동'], dtype='<U3'),
 array([1, 0, 3, 2], dtype=int64),
 array([1, 2, 1, 2], dtype=int64))

In [16]:
#np.ndarray.astype()함수
#넘파이 배열의 타입을 주어진 타입으로 변경해서 새로운 배열 반환
names_[1].dtype

dtype('int64')

In [19]:
names_1=names_[1].astype(np.float32)#변환된 새로운 배열 반환
names_1.dtype
names_1

array([1., 0., 3., 2.], dtype=float32)

In [20]:
import pandas as pd

In [24]:
data = {'A':(1,2,3),'B':(4,5,6)}
df = pd.DataFrame(data)
df
#df_=df.astype(np.float32)#전체 요소를 변환
df_=df.astype({'A':np.float32,'B':np.float64})#컬럼별로 타입변환 가능(넘파이의 astype과 다르다)
df_
df_['A'].dtype,df_['B'].dtype

(dtype('float32'), dtype('float64'))