In [1]:
import numpy as np

In [2]:
#넘파이 배열 변경하기 3 - 넘파이 배열들 합치거나 쪼개기
#1. 합치기 : concatenate() 혹은 vstack()/hstack()함수
arr1 = np.arange(1,11).reshape(2,-1)
arr2 = np.arange(1,11).reshape(2,-1)
arr1


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
#axis지정하지 않은 경우 - 행방향으로 결합
np.concatenate((arr1,arr2))#반드시 괄호로 감싸고 동일한 shape이어야 한다.np.append(arr1,arr2,axis=0)와 같다
np.vstack((arr1,arr2))#위와 같다

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.concatenate((arr1,arr2),axis=1)#반드시 괄호로 감싸고 동일한 shape이어야 한다.np.append(arr1,arr2,axis=1)와 같다
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [9]:
#쪼개기 : hsplit()/vsplit()함수
arr3 = np.arange(0,30).reshape(5,-1)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [20]:
#두번째 인자는 쪼갤 배열의 수(열의 수 % 쪼갤 배열의 수 == 0이어야 한다)
#예: 6(열의 수) 임으로 1,2,3,6 가능( 6 % 1는 0이 아니지만 1은 전체 넘파이 배열을 요소로하는 리스트반환)
#쪼개진 넘파이 배열을 요소로갖는 리스트 반환
hsplit=np.hsplit(arr3,2)#행방향으로 2개로 쪼갠다
hsplit[0].shape

(5, 3)

In [21]:
hsplit=np.hsplit(arr3,6)#행방향으로 6개로 쪼갠다
hsplit

[array([[ 0],
        [ 6],
        [12],
        [18],
        [24]]),
 array([[ 1],
        [ 7],
        [13],
        [19],
        [25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3],
        [ 9],
        [15],
        [21],
        [27]]),
 array([[ 4],
        [10],
        [16],
        [22],
        [28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [26]:
np.vsplit(arr3,5)#열방향으로 쪼갠다.즉 수평방향.행의 수 % 쪼갤 배열의 수 == 0이어야 한다


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]])]

In [27]:
#https://numpy.org/doc/stable/reference/generated/numpy.split.html
#np.hsplit(배열,[x,y,z])
#[x,y,z]은 1차원배열이어야 하고 x,y,z는 오름차순으로 정렬된 int여야한다.
#(hsplit()인 경우 x,y,z는 열 인덱스다)
#즉 아래처럼 분리된다
#[:,:x]
#[:,x:y]
#[:,y:z]
#[:,z:...] 총 4개의 넘파이 배열로 분리된다
#x,y,z는 hsplit()이면 열 인덱스고 vsplit()면 행 인덱스다
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
np.hsplit(arr3,[1,3,5])#[:,:1],[:,1:3],[:,3:5],[:,5:]총 4개로 쪼개진다

[array([[ 0],
        [ 6],
        [12],
        [18],
        [24]]),
 array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [29]:
np.hsplit(arr3,[1,3])#[:,:1],[:,1:3],[:,3:] 3개의 배열로 쪼개짐

[array([[ 0],
        [ 6],
        [12],
        [18],
        [24]]),
 array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29]])]

In [31]:
#전치 :T 전치(Transepose) 사용
print(arr1)
print(arr1.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
