In [4]:
import numpy as np
#Numpy배열 생성하기 2 : 특정값으로 초기화 하는 함수
#zeros()함수:모든 요소를 0로 초기화.데이타 타입 디폴트는 np.float64
zeros = np.zeros(shape=5)#shape=(5,)혹은 shape=[5]
zeros

array([0., 0., 0., 0., 0.])

In [5]:
f'type:{type(zeros)},shape:{zeros.shape},dimensions:{zeros.ndim},dtype:{zeros.dtype}'

"type:<class 'numpy.ndarray'>,shape:(5,),dimensions:1,dtype:float64"

In [6]:
#zeros_like()함수:zeros_like()함수의 인자로 주어진 배열과 같은(like) shape와 dtype 및 ndim을 가진 배열을 생성하고 모든 요소를 0로 초기화
zeros_like = np.zeros_like([[1,2,3],[4,5,6]])
zeros_like

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
f'type:{type(zeros_like)},shape:{zeros_like.shape},dimensions:{zeros_like.ndim},dtype:{zeros_like.dtype}'

"type:<class 'numpy.ndarray'>,shape:(2, 3),dimensions:2,dtype:int32"

In [8]:
#ones()함수:모든 요소를 1로 초기화.데이타 타입 디폴트는 np.float64
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [9]:
f'type:{type(ones)},shape:{ones.shape},dimensions:{ones.ndim},dtype:{ones.dtype}'

"type:<class 'numpy.ndarray'>,shape:(5,),dimensions:1,dtype:float64"

In [10]:
#ones_like()함수:ones_like()함수의 인자로 주어진 배열과 같은(like) shape와 dtype 및 ndim을 가진 배열을 생성하고 모든 요소를 1로 초기화
ones_like = np.ones_like([[1,2,3],[4,5,6]])
ones_like

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
#full()함수:주어진 shape의 배열을 생성하고 모든 요소를 지정한 "fill_value"로 초기화
full = np.full(shape=(2,3),fill_value=10,dtype=np.float32)
full

array([[10., 10., 10.],
       [10., 10., 10.]], dtype=float32)

In [14]:
#full_like()함수:full_like()함수의 인자로 주어진 배열과 같은(like) shape와 dtype 및 ndim을 가진 배열을 생성하고 모든 요소를 fill_value로 초기화
full_like = np.full_like([[1,2,3],[4,5,6]],fill_value=10,dtype=np.float32)
full_like

array([[10., 10., 10.],
       [10., 10., 10.]], dtype=float32)

In [15]:
#empty()함수:임의의 값을 가진 넘파이 배열이 생성.데이타 타입 디폴트는 np.float64
empty = np.empty((3,3))
empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.82208070e-321],
       [1.24610723e-306, 1.29061142e-306, 5.53353523e-322]])