In [2]:
import numpy as np

In [9]:
#넘파이 배열 변경하기 2 - 배열의 요소 변경
#append() 함수
#배열의 끝에 값을 추가하는 함수.
#axis로 값이 추가되는 방향을 설정 가능.
#axis를 지정하지 않으면 1차원 배열로 변경되어 추가
np.random.seed(42)#랜덤값 고정
arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,10,size=(3,4))
arr3 = np.random.randint(1,10,size=(2,3,2))
arr3

array([[[3, 7],
        [4, 9],
        [3, 5]],

       [[3, 7],
        [5, 9],
        [7, 2]]])

In [12]:
#axis를 지정하지 않는 경우:모든 차원이 1차원 배열로 변경되어 추가된다
np.append(arr1,99)

array([ 7,  4,  8,  5,  7,  3,  7,  8,  5,  4,  8,  8, 99])

In [13]:
np.append(arr3,99)

array([ 3,  7,  4,  9,  3,  5,  3,  7,  5,  9,  7,  2, 99])

In [16]:
print('arr1:',arr1)
print('arr2:',arr2)
np.append(arr1,arr2)

arr1: [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]]
arr2: [[3 6 5 2]
 [8 6 2 5]
 [1 6 9 1]]


array([[10, 10, 13,  7],
       [15,  9,  9, 13],
       [ 6, 10, 17,  9]])

In [15]:
np.append(arr1,arr3)

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 4, 8, 8, 3, 7, 4, 9, 3, 5, 3, 7, 5, 9,
       7, 2])

In [18]:
#axis를 지정한 경우-추가하려는 값은(스칼라는 불가-브로그캐스팅이 일어나지 않는다) shape이 같아야 한다.
np.append(arr1,arr2,axis=0)#행축으로 추가 6 x 4

array([[7, 4, 8, 5],
       [7, 3, 7, 8],
       [5, 4, 8, 8],
       [3, 6, 5, 2],
       [8, 6, 2, 5],
       [1, 6, 9, 1]])

In [19]:
np.append(arr1,arr2,axis=1)

array([[7, 4, 8, 5, 3, 6, 5, 2],
       [7, 3, 7, 8, 8, 6, 2, 5],
       [5, 4, 8, 8, 1, 6, 9, 1]])

In [24]:
#np.append(arr1,arr2.reshape(2,-1),axis=1)
#np.append(arr1,99,axis=0)#axis지정시 스칼라 불가

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [28]:
#insert() 함수
#배열의 특정 위치에 값을 삽입하는 함수.
#axis로 값이 삽입되는 방향을 설정 가능.
#axis를 지정하지 않으면 1차원 배열로 변경되어 삽입
#obj:삽입할 위치(일차원 인덱스),values:삽입할 값
np.insert(arr1,obj=4,values=77)

(13,)

In [29]:
arr2

array([[3, 6, 5, 2],
       [8, 6, 2, 5],
       [1, 6, 9, 1]])

In [35]:
np.insert(arr1,obj=4,values=np.array([1,2,3]))

array([7, 4, 8, 5, 1, 2, 3, 4, 5, 7, 3, 7, 8, 5, 4, 8, 8])

In [42]:
#axis를 지정한 경우-삽입하려는 값은 차원이 달라도 된다
#obj:행인덱스 axis=0인 축에서의 인덱스

print(np.insert(arr1,obj=1,values=100,axis=0))#100이 행인덱스 1번위치에 열의 수와 같게 1차원으로 브로드 캐스팅되서 [100,100,100,100추가된다
np.insert(arr1,obj=2,values=[1,2,3,4],axis=0)#추가하려는 1차원의 열의수는 arr1과 같아야 한다


[[  7   4   8   5]
 [100 100 100 100]
 [  7   3   7   8]
 [  5   4   8   8]]


array([[7, 4, 8, 5],
       [7, 3, 7, 8],
       [1, 2, 3, 4],
       [5, 4, 8, 8]])

In [44]:
print(np.insert(arr1,obj=1,values=100,axis=1))#100이 열인덱스 1번 위치에 행의수와 같게 1차원으로 브로드 캐스팅되서 [100,100,100]추가된다
np.insert(arr1,obj=2,values=[1,2,3],axis=1)

[[  7 100   4   8   5]
 [  7 100   3   7   8]
 [  5 100   4   8   8]]


array([[7, 4, 1, 8, 5],
       [7, 3, 2, 7, 8],
       [5, 4, 3, 8, 8]])

In [45]:
#delete() 함수
#배열의 특정 위치의 요소를 삭제하는 함수.
#axis로 방향을 설정 가능.
#axis를 지정하지 않으면 1차원 배열로 변경되어 삭제

In [47]:
np.delete(arr1,9)#9는 1차원으로 플래툰시의 삭제할 인덱스

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 8, 8])

In [50]:
print(arr1)
np.delete(arr1,(1,3,5,7,9))#(1,3,5,7,9)삭제할 요소의 인덱스(1차원으로 플래툰시)

[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]]


array([7, 8, 7, 7, 5, 8, 8])

In [51]:
#axis를 지정한 경우-삭제하려는 값은 차원이 달라도 된다
#obj:행인덱스 axis=0인 축에서의 인덱스
np.delete(arr1,obj=1,axis=0)#1행 삭제

array([[7, 4, 8, 5],
       [5, 4, 8, 8]])

In [52]:
np.delete(arr1,obj=(0,2),axis=0)#0행 및 2행 삭제

array([[7, 3, 7, 8]])

In [53]:
np.delete(arr1,obj=1,axis=1)#1열 삭제

array([[7, 8, 5],
       [7, 7, 8],
       [5, 8, 8]])

In [54]:
np.delete(arr1,obj=(0,2),axis=1)#0열 및 2열 삭제

array([[4, 5],
       [3, 8],
       [4, 8]])