In [1]:
import numpy as np

In [4]:
#넘파이 배열 요소 참조 - 인덱스로 참조(인덱싱)
#[]사용하여 인덱스로 배열의 하나의 요소를 참조하여 값을 변경하거나 읽어 올 수 있다.
#1차원 배열-읽기
nparr = np.arange(5)
nparr

array([0, 1, 2, 3, 4])

In [42]:
nparr[2]
nparr[len(nparr)-1]
nparr[-1]

4

In [11]:
#nparr[len(nparr)]#IndexError: index 5 is out of bounds for axis 0 with size 5

In [14]:
#1차원 배열-쓰기
nparr[0]=10
print(nparr[0])
nparr[0]+=10
nparr[0]

10


20

In [19]:
nparr2 = np.array([list(range(1,6)),list(range(6,11))])
nparr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
#2차원 배열-읽기 [행][열] 아니라 [행,열]식으로 접근
nparr2[0,2]

3

In [21]:
#2차원 배열-쓰기
nparr2[0,2]*=100
nparr2[0,2]

300

In [23]:
nparr3 =np.array(
    [
            [
              [1,2,3],
              [4,5,6],
              [7,8,9]                
            ]
        
    ]
)
nparr3.shape

(1, 3, 3)

In [25]:
#3차원 배열-읽기 차원에서 [axix 0의 인덱스,axis 1의 인덱스,axis 2의 인덱스]
nparr3[0,2,1]#axis 0는 인덱스 0,axis 1는 인덱스 2,axis 2는 인덱스 1 위치값 읽기

8

In [28]:
#3차원 배열-쓰기
nparr3[0,1,1]=50
nparr3

array([[[ 1,  2,  3],
        [ 4, 50,  6],
        [ 7,  8,  9]]])

In [29]:
#넘파이 배열 요소 참조 - 슬라이싱
'''
[시작인덱스:끝인덱스]사용하여 배열의 여러개 요소를 참조할때 사용하는 접근방법이 슬라이싱이다
시작인덱스 생략시 0으로 처리되고
끝인덱스 생략시 마지막 인덱스로 처리된다
그래서 [:]는 전체 범위를 의미한다. 
인덱스를 음수로 지정시에는 끝에서 시작하는 요소의 위치를 뜻한다
즉 -1은 마지막 인덱스를 의미한다
'''
#1차원 배열 슬라이싱
#1차원 배열의 슬라이싱는 오로지 열의 인덱스만을 의미
# 즉 [열번호:열번호]나  [:열번호] 등으로 슬라이싱한다
nparr

array([20,  1,  2,  3,  4])

In [37]:
nparr[1:4]
print(nparr[1:1])#[]
print(nparr[1:])
print(nparr[:4])
print(nparr[1:-1])
print(nparr[:])

[]
[1 2 3 4]
[20  1  2  3]
[1 2 3]
[20  1  2  3  4]


In [35]:
#2차원 배열 슬라이싱
# 2차원 배열의 인덱스는 반드시 [  ,  ] 콤마를 기준으로
# 2개의 인자를 갖는다.첫번째 인자는 행의 인덱스를 의미
# 하고 두번째 인자는 열의 인덱스를 의미한다
# [행인덱스,열인덱스] 행인덱스와 열인덱스 두 곳에 : 이 포함되면 2차원 OUTPUT
#                  행인덱스와 열인덱스 둘 중 하나에 숫자 하나가 지정되면 1차원 OUTPUT
#즉 범위를 슬라이싱하는 :이 각 행렬 인덱스 자리에 존재하면 차원은 유지가된다
#단,:이 빠지면 차원이 줄어 든다
nparr2

array([[  1,   2, 300,   4,   5],
       [  6,   7,   8,   9,  10]])

In [50]:
print(nparr2[0:1,2:4])
print(nparr2[:,2:4])
print(nparr2[0:1,:])
print(nparr2[0:1,2])
print(nparr2[1,2:4])
print(nparr2[:,-1])
print(nparr2[:,:])
score =np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

Train_set = score[:,:-1]
print(Train_set)
Test_set  = score[:,-1]
print(Test_set)

[[300   4]]
[[300   4]
 [  8   9]]
[[  1   2 300   4   5]]
[300]
[8 9]
[ 5 10]
[[  1   2 300   4   5]
 [  6   7   8   9  10]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[ 4  8 12]


In [49]:
#3차원 배열 슬라이싱
#3차원인 경우 [axix 0의 인덱스,axis 1의 인덱스,axis 2의 인덱스]
nparr3= np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ]
        ,
        [
            [7,8,9],
            [10,11,12]
        ]
        ,
        [
            [13,14,15],
            [16,17,18]
        ]
    ])
print(nparr3.shape)


(3, 2, 3)


In [56]:
#각 축 자리에 범위 슬라이싱을 의미는 : 이 없으면 차원이 줄어든다
print(nparr3[1:2,0:1,1:2])
print(nparr3[:,:,1])
print(nparr3[:,1,1])
print(nparr3[:,:,-1])

[[[8]]]
[[ 2  5]
 [ 8 11]
 [14 17]]
[ 5 11 17]
[[ 3  6]
 [ 9 12]
 [15 18]]


In [59]:
#넘파이 배열 요소 참조 - 불리언 인덱싱
#배열 요소의  선택여부를 True,False로 지정하는 방식으로 True에 해당하는 요소만 참조
scores = np.array(
    [
        [99,80,60],
        [78,90,90],
        [100,50,40]
    ])
students = np.array(['가길동','나길동','다길동'])
mask =(students == '나길동')#마스크(불리언 배열)
mask

array([False,  True, False])

In [61]:
'''
마스크(불리언 배열)를 배열을 슬라이싱 하는데 사용한다
True에 해당하는 열 혹은 행만 슬라이싱 할 수 있다
슬라이싱인 [행인덱스,열인덱스]에 행인덱스 혹은 열인덱스 자리에 불리언배열(마스크)를 적용한다:불리언 인덱싱
나길동의 점수만 뽑아오자(나길동의 인덱스를 모른다고 가정시)
'''
nakildong = scores[mask,:]
nakildong

array([[78, 90, 90]])

In [63]:
#수학 점수가 90점 미만인 학생의 국영수 점수 뽑기.
mask = scores[:,-1] < 90
mask

array([ True, False,  True])

In [64]:
scores[mask,:]

array([[ 99,  80,  60],
       [100,  50,  40]])